trunk/smarthome/mydepot/config/routes.rb
Mydepot::Application.routes.draw do

   resources :products
   resources :carts
   resources :orders
   resources :line_items

   scope '(:locale)' do
     root :to => 'store#index', :as => 'store'
   end

   match 'test/mytest', :to => 'line_items#test', :as => 'testas', :via => [:get, :post]

  root :to => 'welcome#index'

end

trunk/smarthome/mydepot/app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = ["Check", "Credit Card", "Purchase Order"]

  attr_accessible :name, :address, :email, :pay_type

  has_many :line_items, :dependent => :destroy

  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

end

trunk/smarthome/mydepot/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
     @orders = Order.paginate :page => params[:page], :order => 'created_at desc', :per_page => 10
  end

  def new
    @order = Order.new

    respond_to do |format|
      format.html
      format.xml {render :xml => @order }
    end
  end

  def update

  end

  def create
    @order = Order.new(params[:order])
    @order.add_line_items_from_cart(current_cart)

    puts  @order.inspect
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        Notifier.order_received(@order).deliver
        format.html { redirect_to(store_url, :notice => 'Thank you for your order!') }
        format.xml { render :xml => @order,  :status => :created, :location =>@order }
      else
        format.html {render :action => "new"}
        format.xml {render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy

  end
end

trunk/smarthome/mydepot/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error")%> prohibited this product from being saved: </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg|  %>
          <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
   <%= f.label :name %><br/>
   <%= f.text_field :name, :size => 40 %>
</div>
 <div class="field">
   <%= f.label :address %><br/>
   <%= f.text_area :address, :rows => 3 , :cols => 40 %>
</div>
 <div class="field">
   <%= f.label :email %><br/>
   <%= f.text_field :email, :size => 40 %>
</div>
 <div class="field">
   <%= f.label :pay_type %><br/>
   <%= f.select :pay_type, Order::PAYMENT_TYPES,
                :prompt => 'Select a payment method' %>
</div>

 <div class="actions">
   <%= f.submit 'Place Order'%>
</div>

<% end %>

trunk/smarthome/mydepot/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Item count</th>
    <th>Name</th>
    <th>Email</th>
    <th>Pay type</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @orders.each do |order| %>
      <tr><% order.line_items.count %>  </tr>
      <tr><% order.name %>  </tr>
      <tr><% order.address %>  </tr>
      <tr><% order.email %>  </tr>
      <tr><% order.pay_type %>  </tr>
      <tr><% total_cost(order.line_items) %>  </tr>
      <td><% link_to 'Show', order %></td>
      <td><% link_to 'Edit', edit_order_path(order) %></td>
      <td><% link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete %></td>
  <% end %>
</table>

trunk/smarthome/mydepot/app/views/orders/new.html.erb
<div class="depot_form">
  <fieldset>
    <legend>please enter your information</legend>
    <%= render 'form' %>
    <%= link_to 'Back' , orders_path%>
  </fieldset>
</div>