trunk/projects/fat_free_crm/config/routes.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
Rails.application.routes.draw do
  resources :lists

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup

  match '/home/options',  :as => :options
  match '/home/toggle',   :as => :toggle
  match '/home/timeline', :as => :timeline
  match '/home/timezone', :as => :timezone
  match '/home/redraw',   :as => :redraw

  resource  :authentication
  resources :comments, :except => [:new, :show]
  resources :emails
  resources :passwords

  resources :accounts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      get  :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put  :attach
      put  :promote
      put  :reject
    end

    get :autocomplete_account_name, :on => :collection
  end

  resources :opportunities, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, :id => /\d+/ do
    collection do
      post :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users, :id => /\d+/ do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
      post :redraw
    end

    collection do
      match :auto_complete
    end
    collection do
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, :except => :index do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        post :auto_complete
        get :options
        post :redraw
        post :sort
        get :subform
      end
    end

    resources :tags do
      member do
        get :confirm
      end
    end

    resources :fields, :as => :custom_fields
    resources :fields, :as => :core_fields

    resources :settings
    resources :plugins
  end

  get '/:controller/tagged/:id' => '#tagged'
end

trunk/projects/fat_free_crm/app/controllers/entities/opportunities_controller.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class OpportunitiesController < EntitiesController
  before_filter :load_settings
  before_filter :get_data_for_sidebar, :only => :index
  before_filter :set_params, :only => [ :index, :redraw, :filter ]

  # GET /opportunities
  #----------------------------------------------------------------------------
  def index
    @opportunities = get_opportunities(:page => params[:page], :per_page => params[:per_page])

    respond_with @opportunities do |format|
      format.xls { render :layout => 'header' }
      format.csv { render :csv => @opportunities }
    end
  end

  # GET /opportunities/1
  # AJAX /opportunities/1
  #----------------------------------------------------------------------------
  def show
    @comment = Comment.new
    @timeline = timeline(@opportunity)
    respond_with(@opportunity)
  end

  # GET /opportunities/new
  #----------------------------------------------------------------------------
  def new
    @opportunity.attributes = {:user => current_user, :stage => Opportunity.default_stage, :access => Setting.default_access, :assigned_to => nil}
    @account     = Account.new(:user => current_user, :access => Setting.default_access)
    @accounts    = Account.my.order('name')

    if params[:related]
      model, id = params[:related].split('_')
      if related = model.classify.constantize.my.find_by_id(id)
        instance_variable_set("@#{model}", related)
        @account = related.account if related.respond_to?(:account) && !related.account.nil?
        @campaign = related.campaign if related.respond_to?(:campaign)
      else
        respond_to_related_not_found(model) and return
      end
    end

    respond_with(@opportunity)
  end

  # GET /opportunities/1/edit                                              AJAX
  #----------------------------------------------------------------------------
  def edit
    @account  = @opportunity.account || Account.new(:user => current_user)
    @accounts = Account.my.order('name')

    if params[:previous].to_s =~ /(\d+)\z/
      @previous = Opportunity.my.find_by_id($1) || $1.to_i
    end

    respond_with(@opportunity)
  end

  # POST /opportunities
  #----------------------------------------------------------------------------
  def create
    @comment_body = params[:comment_body]
    respond_with(@opportunity) do |format|
      if @opportunity.save_with_account_and_permissions(params)
        @opportunity.add_comment_by_user(@comment_body, current_user)
        if called_from_index_page?
          @opportunities = get_opportunities
          get_data_for_sidebar
        elsif called_from_landing_page?(:accounts)
          get_data_for_sidebar(:account)
        elsif called_from_landing_page?(:campaigns)
          get_data_for_sidebar(:campaign)
        end
      else
        @accounts = Account.my.order('name')
        unless params[:account][:id].blank?
          @account = Account.find(params[:account][:id])
        else
          if request.referer =~ /\/accounts\/(.+)$/
            @account = Account.find($1) # related account
          else
            @account = Account.new(:user => current_user)
          end
        end
        @contact = Contact.find(params[:contact]) unless params[:contact].blank?
        @campaign = Campaign.find(params[:campaign]) unless params[:campaign].blank?
      end
    end
  end

  # PUT /opportunities/1
  #----------------------------------------------------------------------------
  def update
    respond_with(@opportunity) do |format|
      if @opportunity.update_with_account_and_permissions(params)
        if called_from_index_page?
          get_data_for_sidebar
        elsif called_from_landing_page?(:accounts)
          get_data_for_sidebar(:account)
        elsif called_from_landing_page?(:campaigns)
          get_data_for_sidebar(:campaign)
        end
      else
        @accounts = Account.my.order('name')
        if @opportunity.account
          @account = Account.find(@opportunity.account.id)
        else
          @account = Account.new(:user => current_user)
        end
      end
    end
  end

  # DELETE /opportunities/1
  #----------------------------------------------------------------------------
  def destroy
    if called_from_landing_page?(:accounts)
      @account = @opportunity.account   # Reload related account if any.
    elsif called_from_landing_page?(:campaigns)
      @campaign = @opportunity.campaign # Reload related campaign if any.
    end
    @opportunity.destroy

    respond_with(@opportunity) do |format|
      format.html { respond_to_destroy(:html) }
      format.js   { respond_to_destroy(:ajax) }
    end
  end

  # PUT /opportunities/1/attach
  #----------------------------------------------------------------------------
  # Handled by EntitiesController :attach

  # POST /opportunities/1/discard
  #----------------------------------------------------------------------------
  # Handled by EntitiesController :discard

  # POST /opportunities/auto_complete/query                                AJAX
  #----------------------------------------------------------------------------
  # Handled by ApplicationController :auto_complete

  # POST /opportunities/redraw                                             AJAX
  #----------------------------------------------------------------------------
  def redraw
    @opportunities = get_opportunities(:page => 1, :per_page => params[:per_page])
    set_options # Refresh options

    respond_with(@opportunities) do |format|
      format.js { render :index }
    end
  end

  # POST /opportunities/filter                                             AJAX
  #----------------------------------------------------------------------------
  def filter
    @opportunities = get_opportunities(:page => 1, :per_page => params[:per_page])
    respond_with(@opportunities) do |format|
      format.js { render :index }
    end
  end

private

  #----------------------------------------------------------------------------
  alias :get_opportunities :get_list_of_records

  #----------------------------------------------------------------------------
  def respond_to_destroy(method)
    if method == :ajax
      if called_from_index_page?
        get_data_for_sidebar
        @opportunities = get_opportunities
        if @opportunities.blank?
          @opportunities = get_opportunities(:page => current_page - 1) if current_page > 1
          render :index and return
        end
      else # Called from related asset.
        self.current_page = 1
      end
      # At this point render destroy.js
    else
      self.current_page = 1
      flash[:notice] = t(:msg_asset_deleted, @opportunity.name)
      redirect_to opportunities_path
    end
  end

  #----------------------------------------------------------------------------
  def get_data_for_sidebar(related = false)
    if related
      instance_variable_set("@#{related}", @opportunity.send(related)) if called_from_landing_page?(related.to_s.pluralize)
    else
      @opportunity_stage_total = { :all => Opportunity.my.count, :other => 0 }
      @stage.each do |value, key|
        @opportunity_stage_total[key] = Opportunity.my.where(:stage => key.to_s).count
        @opportunity_stage_total[:other] -= @opportunity_stage_total[key]
      end
      @opportunity_stage_total[:other] += @opportunity_stage_total[:all]
    end
  end

  #----------------------------------------------------------------------------
  def load_settings
    @stage = Setting.unroll(:opportunity_stage)
  end

  #----------------------------------------------------------------------------
  def set_params
    current_user.pref[:opportunities_per_page] = params[:per_page] if params[:per_page]
    current_user.pref[:opportunities_sort_by]  = Opportunity::sort_by_map[params[:sort_by]] if params[:sort_by]
    session[:opportunities_filter] = params[:stage] if params[:stage]
  end
end

trunk/projects/fat_free_crm/app/helpers/opportunities_helper.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
module OpportunitiesHelper

  # Sidebar checkbox control for filtering opportunities by stage.
  #----------------------------------------------------------------------------
  def opportunity_stage_checkbox(stage, count)
    entity_filter_checkbox(:stage, stage, count)
  end

  # Opportunity summary for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def opportunity_summary(opportunity)
    summary, amount = [], []
    summary << (opportunity.stage ? t(opportunity.stage) : t(:other))
    summary << number_to_currency(opportunity.weighted_amount, :precision => 0)
    unless %w(won lost).include?(opportunity.stage)
      amount << number_to_currency(opportunity.amount || 0, :precision => 0)
      amount << (opportunity.discount ? t(:discount_number, number_to_currency(opportunity.discount, :precision => 0)) : t(:no_discount))
      amount << t(:probability_number, (opportunity.probability || 0).to_s + '%')
      summary << amount.join(' ')
    end
    if opportunity.closes_on
      summary << t(:closing_date, l(opportunity.closes_on, :format => :mmddyy))
    else
      summary << t(:no_closing_date)
    end
    summary.compact.join(', ')
  end
end

trunk/projects/fat_free_crm/app/views/opportunities/_edit.html.haml
.remote
  = simple_form_for(@opportunity, :html => one_submit_only, :remote => true) do |f|
    = link_to_close edit_opportunity_path(@opportunity)
    = f.hidden_field :user_id
    = f.hidden_field :campaign_id

    = f.error_messages :object_name => t('opportunity')

    = render "opportunities/top_section", :f => f, :edit => true
    = render "fields/edit_custom_field_group", :f => f, :edit => true
    = render "fields/groups",             :f => f, :edit => true
    = render "entities/permissions",      :f => f, :edit => true, :entity => @opportunity

    .buttonbar
      = f.submit t(:save_opportunity), :onclick => %/$("account_assigned_to").value = $F("opportunity_assigned_to");/
      #{t :or}
      = link_to_cancel edit_opportunity_path(@opportunity)

trunk/projects/fat_free_crm/app/views/opportunities/_index_long.html.haml
%li.highlight[opportunity]
  - if opportunity.stage
    .strip{:class => opportunity.stage}= t(opportunity.stage)
  - else
    .strip.white #{t :other}

  %ul.tools
    - if can?(:update, opportunity)
      %li= link_to_edit(opportunity)

    - if shown_on_landing_page?
      %li= link_to_discard(opportunity)

    - if can?(:destroy, opportunity)
      %li= link_to_delete(opportunity)

  .indent
    = link_to_if can?(:read, opportunity), opportunity.name, opportunity
    - if (account = opportunity.account) && account.id
      == #{t :from} #{link_to_if can?(:read, account), account.name, account_path(account)}
    %tt
      &ndash;
      - user_name = opportunity.user_id == current_user.id ? t(:me) : opportunity.user.try(:full_name)
      - if user_name
        = t(:added_by, :time_ago => time_ago_in_words(opportunity.created_at), :user => user_name)
      - else
        = t(:added_ago, :value => time_ago_in_words(opportunity.created_at))

    %dt
      %b= number_to_currency(opportunity.weighted_amount, :precision => 0) + " | "
      - won_or_lost = %w(won lost).include?(opportunity.stage)
      - unless won_or_lost
        = number_to_currency(opportunity.amount || 0, :precision => 0)
        - if opportunity.discount
          = t(:discount_number, number_to_currency(opportunity.discount, :precision => 0))
        - else
          = t(:no_discount)
        = t(:probability_number, (opportunity.probability || 0).to_s + '%') + " | "

      - if opportunity.closes_on
        - if won_or_lost
          - if opportunity.closes_on >= Date.today
            = t(:closing_date, l(opportunity.closes_on, :format => :mmddyy))
          - else
            = t(:closed_ago_on, :time_ago => distance_of_time_in_words(opportunity.closes_on, Date.today), :date => l(opportunity.closes_on, :format => :mmddyy))
        - elsif opportunity.closes_on > Date.today
          = t(:expected_to_close,  :time => distance_of_time_in_words(Date.today, opportunity.closes_on), :date => l(opportunity.closes_on, :format => :mmddyy))
        - elsif opportunity.closes_on == Date.today
          %span.warn= t(:closes_today)
        - else
          %span.warn= t(:past_due, distance_of_time_in_words(opportunity.closes_on, Date.today))
      - else
        = t(:no_closing_date)

      - if opportunity.tag_list.present?
        %dt
          .tags= tags_for_index(opportunity)

    = hook(:opportunity_bottom, self, :opportunity => opportunity)

trunk/projects/fat_free_crm/app/views/opportunities/_new.html.haml
= simple_form_for(@opportunity, :html => one_submit_only, :remote => true) do |f|
  = link_to_close new_opportunity_path
  = f.hidden_field :user_id
  = hidden_field_tag "contact",  "#{@contact.id  if @contact}"

  = f.error_messages :object_name => t('opportunity')

  = render "opportunities/top_section", :f => f
  = render "fields/edit_custom_field_group", :f => f
  = render "shared/add_comment",        :f => f
  = render "fields/groups",             :f => f
  = render "entities/permissions",      :f => f, :entity => @opportunity

  .buttonbar
    = f.submit t(:create_opportunity), :onclick => %/$("account_assigned_to").value = $F("opportunity_assigned_to"); if ($("account_id").visible()) { $("account_id").enable(); }/
    #{t :or}
    = link_to_cancel new_opportunity_path

trunk/projects/fat_free_crm/app/views/opportunities/_opportunities.html.haml
= section(object, :opportunities)
.list#opportunities
  - opportunities = object.opportunities.order('updated_at desc').paginate(:page => 1, :per_page => 20)
  = render :partial => "opportunities/opportunity", :collection => opportunities

= will_paginate opportunities, :id => 'opportunities_pagination', :params => {:action => :opportunities}

trunk/projects/fat_free_crm/app/views/opportunities/_opportunity.html.haml
- if (params['controller'] == 'opportunities') and (template = template_for_current_view).present?
  = render(template, :opportunity => opportunity)
- else
  -# default view
  = render 'opportunities/index_long', :opportunity => opportunity

trunk/projects/fat_free_crm/app/views/opportunities/_title_bar.html.haml
#confirm{ hidden }
.title_tools#menu
  = link_to_inline(:edit_opportunity, edit_opportunity_path(@opportunity), :text => t(:edit)) + " | "
  = link_to_function(t(:delete) + '?', confirm_delete(@opportunity))
.title_tools#buttons
  = view_buttons
.title#edit_opportunity_title
  = h(@opportunity.name)
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")

%div#edit_opportunity{ hidden }

trunk/projects/fat_free_crm/app/views/opportunities/_top_section.html.haml
= hook(:opportunity_top_section, self, :f => f) do
  .section
    %table
      %tr
        %td
          .label.req.top #{t :name}:
          = f.text_field :name, :style => "width:325px"
        %td= spacer
        %td
          .label.req.top #{t :stage}:
          = f.select :stage, @stage, { :selected => @opportunity.stage ? @opportunity.stage.to_sym : nil }, { :style => "width:160px" }

    %table{ :border => 0, :width => 500, :cellpadding => 0, :cellspacing => 0 }
      %tr
        %td
          .label #{t :close_date}:
          = f.text_field :closes_on, :value => f.object.closes_on, :style => "width:110px;", :autocomplete => :off, :class => 'date'
        %td= spacer
        %td
          .label #{t :probability} (%):
          = f.text_field :probability, :style => "width:110px; text-align:right;"
        %td= spacer
        %td
          .label #{t :amount} #{t :currency}:
          = f.text_field :amount, :style => "width:110px; text-align:right;"
        %td= spacer
        %td
          .label #{t :discount} #{t :currency}:
          = f.text_field :discount, :style => "width:110px; text-align:right;"

    = fields_for(@account) do |a|
      = a.hidden_field :user_id
      = a.hidden_field :access
      = a.hidden_field :assigned_to
      %table
        %tr
          %td
            != account_select_or_create(a) do |options|
              -# Add [-- None --] account choice when editing existing opportunity that has an account.
              - options[:selected] = @account.id || 0
              - options[:include_blank] = true #t(:select_none) unless @opportunity.new_record? || @opportunity.account.blank?
          %td= spacer
          %td
            .label.req #{t :assigned_to}:
            = user_select(:opportunity, all_users, current_user)
        %tr
          %td
            .label #{t :campaign}:
            = f.collection_select "campaign_id", Campaign.all, :id, :name, { :selected => (@campaign.try(:id) || 0), :include_blank => true }

        - if Setting.background_info && Setting.background_info.include?(:opportunity)
          %tr
            %td(colspan="3")
              .label= t(:background_info) << ':'
              = f.text_area :background_info, :style =>"width:500px", :rows => 3

        = render :partial => "/shared/tags", :locals => {:f => f, :span => 3}

        = hook(:opportunity_top_section_bottom, self, :f => f)

trunk/projects/fat_free_crm/app/views/opportunities/contacts.js.haml
- @contacts = @opportunity.contacts.paginate(:page => params[:page], :per_page => 20)
jQuery('#contacts').html('#{ j render(:partial => 'contacts/contact', :collection => @contacts) }');
jQuery('#contacts_pagination').replaceWith('#{ j will_paginate(@contacts, :id => :contacts_pagination, :params => {:action => :contacts}) }');

trunk/projects/fat_free_crm/app/views/opportunities/create.js.haml
- entity_name = controller.controller_name.singularize.underscore
- @entity = instance_variable_get("@#{entity_name}")
- create_id = "create_#{entity_name}"

- if @entity.valid?
  jQuery('##{create_id}_arrow').html(crm.COLLAPSED);
  jQuery('##{create_id}_title').html('#{ j t(entity_name.pluralize) }');
  jQuery('##{create_id}').slideUp(250);
  jQuery('##{entity_name.pluralize}').prepend('#{ j render(:partial => entity_name, :collection => [ @entity ]) }');
  jQuery('##{dom_id(@entity)}').effect("highlight", { duration:1500 });

  - if called_from_index_page?
    = refresh_sidebar(:index, :filters)
    jQuery('#paginate').html('#{ j render(:partial => "shared/paginate_with_per_page") }');
  - elsif called_from_landing_page?("accounts") # Opportunity created on Account landing page: refresh Account summary.
    - @account.reload
    = refresh_sidebar_for(:accounts, :show, :summary)
  - elsif called_from_landing_page?("campaigns") # Opportunity created on Campaign landing page: refresh Campaign summary.
    - @campaign.reload
    = refresh_sidebar_for(:campaigns, :show, :summary)
  - else # Opportunity created on Contact landing page: refresh recent items list.
    jQuery('#recently').html('#{ j render(:partial => "shared/recently") }');
  crm.flick('empty', 'remove');

- else
  jQuery('##{create_id}').html('#{ j render(:partial => "new") }');
  crm.create_or_select_account(#{ request.referer =~ /\/accounts\// || @account.id.blank? });
  jQuery('##{create_id}').effect("shake", { duration:250, distance: 6 });
  jQuery('#new_#{entity_name} input[type!=hidden]').first().focus();

trunk/projects/fat_free_crm/app/views/opportunities/edit.js.haml
- entity_name = controller.controller_name.singularize.underscore #account
- @entity = instance_variable_get("@#{entity_name}")
- id = dom_id(@entity)

- if params[:cancel].true? # <--------------------- Hide [Edit]

  - if called_from_landing_page?
    crm.flip_form('edit_#{entity_name}');
    crm.set_title('edit_#{entity_name}', '#{h @entity.name}');
  - else                                            # Called from index page...
    jQuery('##{id}').replaceWith('#{ j render(:partial => entity_name, :collection => [ @entity ]) }');

- else # <----------------------------------------- Show requested [Edit Opportunity] form.

  - if params[:cancel].blank?                       # Called from opportunities list item...
    - if @previous                                  # Hide open [Edit Opportunity] form if any.
      - if @previous.is_a?(Opportunity)
        jQuery('##{dom_id(@previous)}').replaceWith('#{ j render(:partial => entity_name, :collection => [ @previous ]) }');
      - else
        crm.flick('#{entity_name}_#{@previous}', 'remove');

    -# Disable onMouseOver for the list item.
    crm.highlight_off('#{id}');
    -# Hide [Create] form if any.
    crm.hide_form('create_#{entity_name}');
    -# Show [Edit] form.
    jQuery('##{id}').html('#{ j render(:partial => "edit") }');

  - elsif params[:cancel].false?                    # Called from title of the opportunity landing page...
    jQuery('#edit_#{entity_name}').html('#{ j render(:partial => "edit") }');
    crm.flip_form('edit_#{entity_name}');
    crm.set_title('edit_#{entity_name}', "#{t :edit} #{h @opportunity.name}");

  crm.create_or_select_account(#{ request.referer =~ /\/accounts\// || @account.id.blank? });
  jQuery('#new_#{entity_name} input[type!=hidden]').first().focus();

trunk/projects/fat_free_crm/app/views/opportunities/new.js.haml
- entity_name = controller.controller_name.singularize
- create_id = "create_#{entity_name}"

crm.flick('empty', 'toggle');
crm.flip_form('#{create_id}');

- unless params[:cancel].true?
  jQuery('##{create_id}').html('#{ j render(:partial => "new") }');
  crm.set_title('#{create_id}', '#{ j t(create_id) }');
  -# this function call is the only difference to normal new.js.haml
  crm.create_or_select_account(#{ request.referer =~ /\/accounts\// || @account.id.blank? });
- else
  crm.set_title('#{create_id}', '#{ j t(entity_name.pluralize) }');

trunk/projects/fat_free_crm/app/views/opportunities/show.html.haml
- if (template = template_for_current_view)
  = render(template, :opportunity => @opportunity)
- else

  -# default view

  = styles_for :task, :contact

  = render 'opportunities/title_bar', :opportunity => @opportunity

  = render "comments/new", :commentable => @opportunity
  = render :partial => "shared/timeline", :collection => @timeline

  = hook(:show_opportunity_bottom, self) do

    = render "tasks/tasks", :object => @opportunity

    = render "contacts/contacts", :object => @opportunity

    = render "versions/versions", :object => @opportunity

    = load_select_popups_for(@opportunity, :tasks, :contacts)

trunk/projects/fat_free_crm/app/views/opportunities/show.js.haml
- entity_name = controller.controller_name.singularize.underscore #account
- @entity = instance_variable_get("@#{entity_name}")

jQuery('#main').html('#{ j (render :template => "#{entity_name.pluralize}/show.html", entity_name => @entity) }');
= raw generate_js_for_popups(@entity, :tasks, :contacts)

trunk/projects/fat_free_crm/app/views/opportunities/update.js.haml
- entity_name = controller.controller_name.singularize.underscore #account
- @entity = instance_variable_get("@#{entity_name}")
- id = called_from_landing_page? ? "edit_#{entity_name}" : dom_id(@entity)

- if @entity.errors.empty?
  - if called_from_landing_page?
    crm.flip_form('edit_#{entity_name}');
    crm.set_title('edit_#{entity_name}', '#{h @entity.name}');
    = refresh_sidebar(:show, :summary)
  - else
    jQuery('##{id}').replaceWith('#{ j render(:partial => entity_name, :collection => [ @entity ]) }');
    jQuery('##{id}').effect("highlight", { duration:1500 });
    - if called_from_index_page?
      = refresh_sidebar(:index, :filters)
    - elsif called_from_landing_page?(:accounts)
      = refresh_sidebar_for(:accounts, :show, :summary)
    - elsif called_from_landing_page?(:campaigns)
      = refresh_sidebar_for(:campaigns, :show, :summary)
    - else
      jQuery('#recently').replaceWith('#{ j render(:partial => "shared/recently") }');
- else
  jQuery('##{id}').html('#{ j render(:partial => "edit") }');
  crm.create_or_select_account(#{ request.referer =~ /\/accounts\// || @account.id.blank? });
  jQuery('##{id}').effect("shake", { duration:250, distance: 6 });
  jQuery('##{dom_id(@entity, :edit)} input[type!=hidden]').first().focus();